from config import PCA,DS
import xlwings as xw
import numpy as np
def pcasave(self):  
    self.appExcel=xw.App()
    wb=xw.books.active
    sht=wb.sheets[0]
    sht.name='DataSet'
    Ts=DS.Ts[DS.Ir]
    Lr=DS.Lr[DS.Ir]
    Lr=Lr[-Ts]
    Lr=Lr[np.newaxis]
    Lc=DS.Lc[DS.Ic]
    Lc=Lc[np.newaxis]
    sht.range('B1').value=Lc
    sht.range('A2').value='mean'
    sht.range('B2').value=PCA.Xm  
    sht.range('A3').value='std'
    sht.range('B3').value=PCA.Xstd
    if(DS.Cl!=None):
        sht.range('B5').value=range(len(DS.Cl))  
        sht.range('A6').value='Group Class'
        sht.range('B6').value=DS.Cl 
    sht.range('A7').value=Lr.T
    sht.range('B7').value=PCA.Xc
    sht=wb.sheets[1]
    sht.name='Loading'
    sht.range('A1').value='n.comp.'
    sht.range('A2').value='Eigenvalues'
    sht.range('A3').value='Residual Var.'
    sht.range('A5').value=Lc.T
    sht.range('B1').value=np.array(range(1,PCA.ncp+1))
    sht.range('B2').value=PCA.ei
    sht.range('B3').value=PCA.rv
    sht.range('B5').value=PCA.lo
    sht=wb.sheets[2]
    sht.name='Scores'
    sht.range('A2').value=Lr.T
    sht.range('B1').value=np.array(range(1,PCA.ncp+1))
    sht.range('B2').value=PCA.sco
    wb.sheets.add(name='Residuals')
    sht=wb.sheets['Residuals']
    sht.range('B1').value=Lc
    sht.range('A2').value=Lr.T
    sht.range('B2').value=PCA.res
    wb.sheets.add(name='T2-Q')
    sht=wb.sheets['T2-Q']
    sht.range('B1').value='T2'
    sht.range('A2').value=Lr.T
    sht.range('B2').value=PCA.ht2[np.newaxis].T
    sht.range('C1').value='Q'
    sht.range('C2').value=PCA.Q[np.newaxis].T        
    wb.sheets.add(name='Qlim-MQ')
    sht=wb.sheets['Qlim-MQ']
    sht.range('A1').value='Qlim(95%)'
    sht.range('A2').value=PCA.Q95
    sht.range('A3').value='Qlim(99%)'
    sht.range('A4').value=PCA.Q99
    sht.range('B1').value='MQ'
    sht.range('B2').value=PCA.MQ
    wb.sheets.add(name='Tlim-MT')
    sht=wb.sheets['Tlim-MT']
    sht.range('A1').value='Tlim(95%)'
    sht.range('A2').value=PCA.T95
    sht.range('A3').value='Tlim(99%)'
    sht.range('A4').value=PCA.T99
    sht.range('B1').value='MT'
    sht.range('B2').value=PCA.MT
    wb.sheets.add(name='SSX')
    sht=wb.sheets['SSX']
    sht.range('B1').value='SSX'
    sht.range('B2').value=PCA.ssx[np.newaxis].T
    sht.range('A2').value=Lc.T
    try:
        wb.sheets.add(name='SSX')
        sht=wb.sheets['SSX']
        sht.range('B2').value=PCA.Xcv
        sht.range('B1').value=Lc
        sht.range('A2').value=Lr.T
    except:
        pass
    try:
        wb.sheets.add(name='Additional')
        sht=wb.sheets['Additional']
        sht.range('B2').value=PCA.TXt
        sht.range('B1').value=np.array(range(1,PCA.ncp+1))
    except:
        pass
